# Generated by Django 3.1 on 2020-12-01 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('idLenguaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombreLenguaje', models.CharField(max_length=200)),
                ('complejidad', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PruebaTecnica',
            fields=[
                ('idPruebaTecnica', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePrueba', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('lenguaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendUsc.lenguaje')),
            ],
        ),
        migrations.CreateModel(
            name='PruebaTecnicaPregunta',
            fields=[
                ('idPruebaPregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pruebaPregunta', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('pruebaReferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendUsc.pruebatecnica')),
            ],
        ),
        migrations.CreateModel(
            name='PruebaTecnicaRespuesta',
            fields=[
                ('idPruebaRespuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=200)),
                ('esValido', models.IntegerField()),
                ('idPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendUsc.pruebatecnicapregunta')),
            ],
        ),
    ]
