# Generated by Django 3.1 on 2020-12-01 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendUsc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('cantidadPersonas', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='pruebatecnica',
            name='lenguaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='backendUsc.lenguaje'),
        ),
        migrations.AlterField(
            model_name='pruebatecnicapregunta',
            name='pruebaReferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta', to='backendUsc.pruebatecnica'),
        ),
        migrations.AlterField(
            model_name='pruebatecnicarespuesta',
            name='idPregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='backendUsc.pruebatecnicapregunta'),
        ),
    ]
