# Generated by Django 3.1 on 2020-12-01 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendUsc', '0002_auto_20201201_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('identificacionUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=200)),
                ('apellidoUsuario', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('correoUsuario', models.CharField(max_length=200)),
                ('facultad', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuarioReserva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to='backendUsc.usuario'),
            preserve_default=False,
        ),
    ]
